-- Create tables
create table if not exists "University" (
  id          integer generated by default as identity primary key,
  unitid      integer unique not null,
  name        text,
  city        text,
  state       text
);

create index if not exists "University_unitid_idx" on "University"(unitid);

create table if not exists "Metric" (
  id    integer generated by default as identity primary key,
  code  text unique not null,
  name  text,
  unit  text
);

create table if not exists "TimeSeries" (
  id            integer generated by default as identity primary key,
  universityId  integer not null references "University"(id) on delete cascade,
  metricId      integer not null references "Metric"(id) on delete cascade,
  year          integer not null,
  value         numeric(20,8),
  unique (universityId, metricId, year)
);

create index if not exists "TimeSeries_metricId_idx" on "TimeSeries"(metricId);
create index if not exists "TimeSeries_uni_year_idx" on "TimeSeries"(universityId, year);
