name: Refresh IPEDS Data
on:
  schedule:
    - cron: "17 9 1 * *"   # monthly
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - name: Run backfill (EF etc.)
        run: node --loader ts-node/esm scripts/backfill.ts
      - name: Revalidate Vercel cache (optional)
        run: |
          if [ -n "${{ secrets.VERCEL_REVALIDATE_ENDPOINT }}" ] && [ -n "${{ secrets.REVALIDATE_SECRET }}" ]; then
            curl -sS -X POST "${{ secrets.VERCEL_REVALIDATE_ENDPOINT }}?tag=metrics&secret=${{ secrets.REVALIDATE_SECRET }}"
          else
            echo "Skipping revalidate; secrets not set."
          fi
